all_roles:
  - "Werwolf-1"
  - "Werwolf-2"
  - "Polarwolf"
  - "Wolfsseher"
  - "Werwolfjunges"
  - "Weißer-Werwolf"
  - "Werschweinchen"
  - "Jason"
  - "Jäger"
  - "Hexe"
  - "Seherin"
  - "Amor"
  - "Dorfdepp"
  - "Rotkäppchen"
  - "Geschwister-1"
  - "Geschwister-2"
  - "Geschwister-3"
  - "Geschwister-4"
  - "Dorfbewohner-1"
  - "Dorfbewohner-2"
  - "Dorfbewohner-3"
  - "Der-Rabe"
  - "tot"
  - "Hauptmann"
  - "Spielleiter"
